inherits:
  - strictness_high

ignore:
  - venv
  - tests
  - .pytest_cache/


output-format: grouped

test-warnings: true
doc-warnings: true

autodetect: false

pep8:
  run: true

pylint:
  run: true
  options:
    ignored-classes: pytest
  disable:
    - C0302
    - missing-module-docstring
    - invalid-name
    - missing-function-docstring
    - logging-too-many-args
    - no-value-for-parameter

pydocstyle:
  disable:
    - D100
    - D103
    - D212